= Модуль `CadesSigner`

Модуль `CadesSigner` предоставляет функции для интеграции поддержки Электронной Цифровой Подписи ("ЭЦП") с использованием алгоритмов, установленных ГОСТ Р 34.10/11/12.

== Содержание

* <<Состав репозитория>>
* <<Установка>>
* <<Описание типов>>
* <<Исключения>>
* <<Функции>>

== Состав репозитория
* Каталог `CadesSigner`: модуль `CadesSigner` и зависимости.  Каталог включает в себя несколько несколько необходимых файлов из библиотеки link:https://sourceforge.net/projects/jedi-apilib/[Jedi jwa]. Этти файлы имеют префикс `Jedi` и они не требуются, если Jedi установлена в полном объёме.
* Каталог `SampleApp`: демонстрационное\тестовое приложение.
* Каталог `Tools`: вспомогательные артефакты разработки, не представлют интереса при интеграции модуля. 

== Установка
Модуль разрабатывался и тестировался с исполльзованием link:https://cryptopro.ru/products/csp[CryptoPro CSP]. 
Соответственно, для сборки и использования модуля CadesSign необходимо установить link:https://cryptopro.ru/products/cades/sdk[КриптоПро ЭЦП SDK]

Новые версии CryptoPro CSP устанавливают свои библиотеки в link:https://docs.cryptopro.ru/cades/usage/cades-manifests?id=%d0%97%d0%b0%d0%b3%d1%80%d1%83%d0%b7%d0%ba%d0%b0-cadesdllxadesdll-%d0%b2-%d0%bf%d1%80%d0%b8%d0%bb%d0%be%d0%b6%d0%b5%d0%bd%d0%b8%d0%b5-%d0%bf%d0%be%d0%bb%d1%8c%d0%b7%d0%be%d0%b2%d0%b0%d1%82%d0%b5%d0%bb%d1%8f-%d1%82%d0%be%d0%bb%d1%8c%d0%ba%d0%be-%d0%b4%d0%bb%d1%8f-windows[режиме изоляции], который не поддержаивается старыми средами разработки, такими как Delphi7 (кажется это так???).
Для работы приложений, разработанных на Delphi7, необходим установка "side-by-side". Говоря по простому, после установки SDK нужно найти библиотеку `cades.dll` и скопировать её в каталог, где будет размещено разрабатываемое приложение. 

== Описание типов

* `TBytes`: Массив байтов, используется для представления содержимого файла и других данных в байтовом формате.
* `T20Bytes`: Массив из 20 байтов, предназначенный для хранения SHA-1 хеш-суммы (отпечатка) сертификата.
* `TCertOption`: Запись, представляющая параметры сертификата.
  * `FriendlyName` - имя сертификата, используемое для отображения и выбора.
  * `Thumbprint` - уникальный идентификатор (отпечаток) сертификата, представленный в виде `T20Bytes`.

=== Исключения

* `ECertificateException`: Исключение, используемое для обработки ошибок при работе с сертификатами и криптографическими операциями.
  * `ErrorCode` - код ошибки из Windows API, который указывает на причину сбоя.

=== Функции

==== `GetCertificates`

[source,delphi]
----
function GetCertificates(const Prefix: string): TList;
----

Возвращает список сертификатов, доступных в системе, на основе указанного префикса `Prefix`.

* *Параметры*:
  ** `Prefix`: Строка, которая используется для фильтрации сертификатов по имени.

* *Результат*:
  ** Возвращает список сертификатов в виде `TList`, содержащий объекты `TCertOption`.

==== `SignFile`

[source,delphi]
----
function SignFile(const FilePath: string; const thumbprint: T20Bytes; const password: string): string;
----

Создает цифровую подпись для файла, используя указанный сертификат.

* *Параметры*:
  ** `FilePath`: Полный путь к файлу, который нужно подписать.
  ** `thumbprint`: Отпечаток (thumbprint) сертификата в формате `T20Bytes`, который будет использоваться для подписи.
  ** `password`: Пароль для доступа к сертификату.

* *Результат*:
  ** Возвращает путь к файлу с цифровой подписью.

=== Примеры использования

[source,delphi]
----
var
  CertList: TList;
  SignaturePath: string;
begin
  // Получение списка сертификатов с префиксом "Test"
  CertList := GetCertificates('Test');
  
  try
    // Подписание файла с использованием сертификата
    SignaturePath := SignFile('C:\Documents\example.pdf', thumbprint, 'password');
    Writeln('Подпись создана и сохранена в: ' + SignaturePath);
  finally
    CertList.Free;
  end;
end;
----

=== Ошибки

При возникновении ошибок во время операций с сертификатами и файлами модуль `CadesSigner` генерирует исключения типа `ECertificateException`, которые содержат сообщение об ошибке и код ошибки. Например, ошибка `ERR_OPEN_STORE_FAILED` указывает на невозможность открытия хранилища сертификатов.

---

Этот README описывает только публичный интерфейс модуля. Подробная документация по внутренним методам, используемым для обработки файлов и криптографических операций, доступна в исходном коде.
