unit AdesConstants;

interface

uses
  Windows,
  SysUtils,
  JwaWinCrypt;

const
  // Flags for ADES options
  ADES_DISABLE_REDUNDANCY               = $00010000;
  ADES_USE_OCSP_AUTHORIZED_POLICY       = $00020000;

  // Verify status codes
  ADES_VERIFY_SUCCESS                    = $00;
  ADES_VERIFY_INVALID_REFS_AND_VALUES    = $01;
  ADES_VERIFY_SIGNER_NOT_FOUND           = $02;
  ADES_VERIFY_NO_VALID_SIGNATURE_TIMESTAMP = $03;
  ADES_VERIFY_REFS_AND_VALUES_NO_MATCH   = $04;
  ADES_VERIFY_NO_CHAIN                   = $05;
  ADES_VERIFY_END_CERT_REVOCATION        = $06;
  ADES_VERIFY_CHAIN_CERT_REVOCATION      = $07;
  ADES_VERIFY_BAD_SIGNATURE              = $08;
  ADES_VERIFY_NO_VALID_CADES_C_TIMESTAMP = $09;
  ADES_VERIFY_BAD_POLICY                 = $0A;
  ADES_VERIFY_UNSUPPORTED_ATTRIBUTE      = $0B;
  ADES_VERIFY_FAILED_POLICY              = $0C;
  ADES_VERIFY_ECONTENTTYPE_NO_MATCH      = $0D;
  ADES_VERIFY_NO_VALID_ARCHIVE_TIMESTAMP = $0E;

  // Timestamp options
  ADES_TIMESTAMP_NO_CERT_REQ             = $00000001;
  ADES_CHECK_CERT_REQ                    = $00000002;
  ADES_SKIP_IE_PROXY_CONFIGURATION       = $00000004;
  ADES_LEGACY_CRL_RETRIEVE               = $00000008;

type
  CADES_BLOB_ARRAY = array of CRYPT_SEQUENCE_OF_ANY;
  PCADES_BLOB_ARRAY = ^CADES_BLOB_ARRAY;

implementation

end.

